### ISSUE TITLE
Quais plataformas serão contempladas?Mobile?Web?Desktop para o gerenciamento do estacioanamento?

### ISSUE THREAD

**Issue by gilberto-009199** [EdsonMostaco/ParkingSpot#4]
Olá, @EdsonMostaco.
Tem algum ideia sobre as plataformas? Se sim quais serão feitas primeiro e quais funcionalidades cada uma tera?
Todas as plataformas possuiram as mesmas funcionalidade?

**Comment by EdsonMostaco** [comment]
A ideia a princípio é fazer um App Desktop e depois expandir para os Apps de Smartphone. A prioridade inicial deve ser o Desktop por permitir a criação de um protótipo de maneira mais simples e rápida.

**Comment by gilberto-009199** [comment]
Então uma aplicação web para acessar via browser

**Comment by EdsonMostaco** [comment]
Sim, uma versão web com uma boa responsividade a principio e posteriormente traduzir para android
